version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.4
    - 2.8.1
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: ipdb
    versions:
    - 0.13.4
    - 0.13.5
    - 0.13.6
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: sqlalchemy-utils
    versions:
    - 0.36.8
- package-ecosystem: npm
  directory: "/superset/assets"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
