version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
      time: "20:00"
    labels:
      - pip
      - dependabot
      - testing
    open-pull-requests-limit: 30
