version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"
    labels:
      - pip
      - dependabot
      - testing
    open-pull-requests-limit: 30
