name: SupersetBot Workflow

on:
  issue_comment:
    types: [created, edited]

  # Making the workflow testable since `issue_comment` only triggers on
  # the default branch
  workflow_dispatch:
    inputs:
      comment_body:
        description: 'Comment Body'
        required: true
        type: string

jobs:
  supersetbot:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@supersetbot'))
    steps:
      - name: Quickly add thumbs up!
        uses: actions/github-script@v5
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/')
            await github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: ${{ github.event.comment.id }},
              content: '+1'
            });
      - name: Execute SupersetBot Command
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install supersetbot
      - uses: actions/github-script@v7
        with:
          script: |
            (async () => {
              const cmd = context.eventName === 'workflow_dispatch'
                ? context.payload.inputs.comment_body
                : context.payload.comment.body;
              const githubWorkspace = process.env.GITHUB_WORKSPACE;
              const modulePath = `${githubWorkspace}/.github/workflows/supersetbot/src/index.js`;
              const { runCommandFromGithubAction } = await import('supersetbot');
              runCommandFromGithubAction(cmd, context, github);
            })();
